---
start_directory: $WORKSPACE
session_name: $PROJECT_NAME

plugins:
  - tmuxp_plugin_loader.plugin.Loader

windows:
  - window_name: editor
    start_directory: .
    layout: even-horizontal
    panes:
      - shell_command:
        - editor ./src/$PROJECT_NAME/.

  - window_name: shell
    start_directory: .
    layout: even-horizontal
    panes:
      - pane
